apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: name-a
spec:
  name: name-b
  predictors:
    - name: name-c
      graph:
        name: model-a
        type: MODEL
        endpoint:
          type: REST
        children: []
      componentSpecs:
        - spec:
            containers:
              - name: model-a
                image: model-a-image
      replicas: 1
